Partial-Views-ASP.Net/Models/ErrorViewModel.cs
namespace Partial_Views_ASP.Net.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Partial-Views-ASP.Net/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Partial_Views_ASP.Net.Models;
using System.Diagnostics;

namespace Partial_Views_ASP.Net.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult About()
        {
            return View();
        }
        public IActionResult Contact()
        {
            return View();
        }
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Partial-Views-ASP.Net/ViewComponents/MarqueeViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Partial_Views_ASP.Net.ViewComponents
{
    public class MarqueeViewComponent:ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var datas = new List<string>()
            {
                "DIZAYN",
                "PROQRAMLAŞDIRMA",
                "KIBER TƏHLÜKƏSİZLİK",
                "UŞAQLAR ÜÇÜN IT"
            };
            return View(datas);
        }
    }
}

Partial-Views-ASP.Net/Views/Home/About.cshtml
<div class="blog-section">
    <div class="body-section d-flex">
        <div class="left-section">
            <h1>Blog</h1>
            <p class="w-50 ">
                İT sahəsində təlim haqqında cari məlumatlar. Biz İT-dəki tendensiyalar, proqramlaşdırma dillərinin reytinqləri,
                İT peşələrini seçmək üçün məsləhətlər və tövsiyələr və daha çox şeylər haqqında danışırıq.
            </p>
        </div>

        <div class="right-section">
            <img src="https://itstep.az/dist/images/academy/blog/man@2x.webp" />
        </div>
    </div>

</div>

Partial-Views-ASP.Net/Views/Home/Contact.cshtml
<div class="contact">
    <div class="contact-content">
        <p class="contact-title">Əlaqə</p>

    </div>

</div>

Partial-Views-ASP.Net/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}


﻿<div class="banner">
    <div class="banner-content">
        <p class="banner-title">STEP IT Academy</p>
        <p class="banner-subtitle">
            Missiyamız: tələbələrimizin gələcək uğurlarının əsasını qoymaq üçün keyfiyyətli və bazarda tələb olunan təhsil
        </p>
    </div>
</div>


<section>
    @await Component.InvokeAsync("Marquee")
</section>

Partial-Views-ASP.Net/Views/Shared/Components/Marquee/Default.cshtml
@model List<string>

<div class="marquee">
    <marquee id="myMarquee" behavior="scroll" direction="left" scrollamount="15">
        @foreach(var item in Model)
        {
            <button class="elements">@item</button> 
        }
    </marquee>
</div>

<script>

    const marquee = document.getElementById('myMarquee');

    function pauseMarquee() {
        marquee.stop();
    }

    function resumeMarquee() {
        marquee.start();
    }
    marquee.addEventListener('mouseenter', pauseMarquee);
    marquee.addEventListener('mouseleave', resumeMarquee);

</script>

Partial-Views-ASP.Net/Views/Shared/FooterPartialView.cshtml
<div class="info-footer-div">
	<div class="first-part">
		<div class="nav-div">
			<h3>Kurslar</h3>
			<nav>
				<a>Dizayn</a>
				<a>Proqramlaşdırma</a>
				<a>Kibertəhlükəsizlik</a>
				<a>Uşaqlar üçün kompüter kursları</a>
				<a>Tətillər</a>
			</nav>
		</div>
		<div class="nav-div">
			<h3>IT Step haqqında</h3>
			<nav>
				<a>Akademiya haqqında</a>
				<a>Rəylər</a>
				<a>Əlaqə</a>
				<a>Blog</a>
				<a>Vakansiyalar</a>
			</nav>
		</div>
		<div class="nav-div">
			<h3>Əlaqə</h3>
			<nav>
				<a>Koroğlu Rəhimov 70</a>
				<a>(012) 599 11 59</a>
				<a>sale_baku</a>
				<a>10:00-18:00 (b.e-ş)</a>
			</nav>
		</div>
	</div>
	<div class="second-part">
		<p>© 1999-2024 STEP IT Academy</p>
		<nav class="media-links">
			<a href="https://www.facebook.com/ITSTEPAcademyBaku"><img src="https://www.edigitalagency.com.au/wp-content/uploads/Facebook-logo-grey-circle-png-transparent.png" /></a>
			<a href="https://www.instagram.com/stepit_baku/"><img src="https://totalpng.com//public/uploads/preview/instagram-grey-logo-png-hd-copy-11656657483bsurpsft3i.png" /></a>
			<a href="https://www.youtube.com/channel/UCiXqv3-JBtRW4hwVibCW8Rg?view_as=subscriber"><img src="https://cdn.pixabay.com/photo/2018/03/19/02/52/the-youtube-logo-3238901_1280.png" /></a>
		</nav>
	</div>
</div>

Partial-Views-ASP.Net/Views/Shared/HeaderPartialView.cshtml
<div class="header">
    <img class="header-logo" src="https://fsx3.itstep.org/api/v1/files/XlNHbfS0RU_exefWDWAnrdXMR5AXEpRT" />
    <div class="header-navbar">
        <a asp-controller="Home" asp-action="About">About</a>
        <a asp-controller="Home" asp-action="Contact">Contact</a>
    </div>
    <div class="header-comboboxes">
        <select>
            <option value="value">Baki</option>
            <option value="value">Kiyev</option>
        </select>
        <select>
            <option value="value">AZ</option>
            <option value="value">RU</option>
        </select>
        <select class="contact-number">
            <option value="value">(012) 599 11 59</option>
        </select>
    </div>
</div>

Partial-Views-ASP.Net/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Partial_Views_ASP.Net</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Partial_Views_ASP.Net.styles.css" asp-append-version="true" />
</head>
<body>
    <partial name="HeaderPartialView.cshtml">
    
    
    <div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    
     <partial name="FooterPartialView.cshtml"/>
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>